version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: comfi
      POSTGRES_DB: dev-db

