import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LogInProvider } from "@/components/context";
import NavBar from "./nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ComFi - Community Finance dApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LogInProvider>
        <body className={inter.className}>
          <div className="flex min-h-screen flex-col items-center justify-around p-24">
            <NavBar />
            {children}
          </div>
        </body>
      </LogInProvider>
    </html>
  );
}
